name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-2-4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build & Publish: 2.4"
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ruby-base
          image-tag: 2.4
          dockerfile: Dockerfile-2.4

  build-2-5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build & Publish: 2.5"
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ruby-base
          image-tag: 2.5
          dockerfile: Dockerfile-2.5

  build-2-6-0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build & Publish: 2.6.0"
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ruby-base
          image-tag: 2.6.0
          dockerfile: Dockerfile-2.6.0

  build-2-6-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Build & Publish: 2.6.3"
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ruby-base
          image-tag: 2.6.3
          dockerfile: Dockerfile-2.6.3

  build-2-7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Build & Publish: 2.7"
        uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ruby-base
          image-tag: 2.7
          dockerfile: Dockerfile-2.7
